version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      - .:/go/build
    depends_on:
      - db
  db:
    image: mysql:8.0
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db_data:
